# Student Performans Analysis #
### This is the final project required for data science nanodegree by GA & Misk Academy ###

- Dataset available at : https://archive.ics.uci.edu/ml/datasets/student+performance
---

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set_style("white")
import statsmodels.api as sm

from sklearn import metrics
from sklearn.metrics import classification_report

## 1. Loading Dataset

In [13]:
# load data files into data frame objects

math=pd.read_csv("./data/student-mat.csv",delimiter=";")
por=pd.read_csv("./data/student-por.csv",delimiter=";")
dictionary=pd.read_excel("./data/dictionary.xlsx")
#merging data frams into one data fram
students=pd.concat([math,por])

In [10]:
#Contents auto-fit
pd.set_option('display.max_colwidth', 0)
dictionary

,Variable,Description
0,school,student's school (binary: 'GP' - Gabriel Pereira or 'MS' - Mousinho da Silveira)
1,sex,student's sex (binary: 'F' - female or 'M' - male)
2,age,student's age (numeric: from 15 to 22)
3,address,student's home address type (binary: 'U' - urban or 'R' - rural)
4,famsize,family size (binary: 'LE3' - less or equal to 3 or 'GT3' - greater than 3)
5,Pstatus,parent's cohabitation status (binary: 'T' - living together or 'A' - apart)
6,Medu,"mother's education (numeric: 0 - none, 1 - primary education (4th grade), 2 - 5th to 9th grade, 3-secondary education or 4 -higher education)"
7,Fedu,"father's education (numeric: 0 - none, 1 - primary education (4th grade), 2(5th to 9th grade), 3-secondary education or 4-higher education)"
8,Mjob,"mother's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')"
9,Fjob,"father's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')"
10,reason,"reason to choose this school (nominal: close to 'home', school 'reputation', 'course' preference or 'other')"
11,guardian,"student's guardian (nominal: 'mother', 'father' or 'other')"
12,traveltime,"home to school travel time (numeric: 1 - <15 min., 2 - 15 to 30 min., 3 - 30 min. to 1 hour, or 4 - >1 hour)"
13,studytime,"weekly study time (numeric: 1 - <2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - >10 hours)"
14,failures,"number of past class failures (numeric: n if 1<=n<3, else 4)"
15,schoolsup,extra educational support (binary: yes or no)
16,famsup,family educational support (binary: yes or no)
17,paid,extra paid classes within the course subject (Math or Portuguese) (binary: yes or no)
18,nursery,attended nursery school (binary: yes or no)
19,activities,extra-curricular activities (binary: yes or no)
20,higher,wants to take higher education (binary: yes or no)
21,internet,Internet access at home (binary: yes or no)
22,romantic,with a romantic relationship (binary: yes or no)
23,famrel,quality of family relationships (numeric: from 1 - very bad to 5 - excellent)
24,freetime,free time after school (numeric: from 1 - very low to 5 - very high)
25,goout,going out with friends (numeric: from 1 - very low to 5 - very high)
26,Dalc,workday alcohol consumption (numeric: from 1 - very low to 5 - very high)
27,Walc,weekend alcohol consumption (numeric: from 1 - very low to 5 - very high)
28,health,current health status (numeric: from 1 - very bad to 5 - very good)
29,absences,number of school absences (numeric: from 0 to 93)
30,G1,first period grade (numeric: from 0 to 20)
31,G2,second period grade (numeric: from 0 to 20)
32,G3,"final grade (numeric: from 0 to 20, output target)"

## 2. Data Attributes and Statistics

In [3]:
students.shape

(1044, 33)

In [12]:
students.dtypes

school        object
sex           object
age           int64
address       object
famsize       object
Pstatus       object
Medu          int64
Fedu          int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime    int64
studytime     int64
failures      int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel        int64
freetime      int64
goout         int64
Dalc          int64
Walc          int64
health        int64
absences      int64
G1            int64
G2            int64
G3            int64
dtype: object

In [4]:
students.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000
mean,16.726054,2.603448,2.387931,1.522989,1.970307,0.264368,3.935824,3.201149,3.156130,1.494253,2.284483,3.543103,4.434866,11.213602,11.246169,11.341954
std,1.239975,1.124907,1.099938,0.731727,0.834353,0.656142,0.933401,1.031507,1.152575,0.911714,1.285105,1.424703,6.210017,2.983394,3.285071,3.864796
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,16.000000,2.000000,1.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,9.000000,9.000000,10.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,2.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,6.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [5]:

students.corr()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
age,1.000000,-0.130196,-0.138521,0.049216,-0.007870,0.282364,0.007162,0.002645,0.118510,0.133453,0.098291,-0.029129,0.153196,-0.124121,-0.119475,-0.125282
Medu,-0.130196,1.000000,0.642063,-0.238181,0.090616,-0.187769,0.015004,0.001054,0.025614,0.001515,-0.029331,-0.013254,0.059708,0.226101,0.224662,0.201472
Fedu,-0.138521,0.642063,1.000000,-0.196328,0.033458,-0.191390,0.013066,0.002142,0.030075,-0.000165,0.019524,0.034288,0.040829,0.195898,0.182634,0.159796
traveltime,0.049216,-0.238181,-0.196328,1.000000,-0.081328,0.087177,-0.012578,-0.007403,0.049740,0.109423,0.084292,-0.029002,-0.022669,-0.121053,-0.140163,-0.102627
studytime,-0.007870,0.090616,0.033458,-0.081328,1.000000,-0.152024,0.012324,-0.094429,-0.072941,-0.159665,-0.229073,-0.063044,-0.075594,0.211314,0.183167,0.161629
failures,0.282364,-0.187769,-0.191390,0.087177,-0.152024,1.000000,-0.053676,0.102679,0.074683,0.116336,0.107432,0.048311,0.099998,-0.374175,-0.377172,-0.383145
famrel,0.007162,0.015004,0.013066,-0.012578,0.012324,-0.053676,1.000000,0.136901,0.080619,-0.076483,-0.100663,0.104101,-0.062171,0.036947,0.042054,0.054461
freetime,0.002645,0.001054,0.002142,-0.007403,-0.094429,0.102679,0.136901,1.000000,0.323556,0.144979,0.130377,0.081517,-0.032079,-0.051985,-0.068952,-0.064890
goout,0.118510,0.025614,0.030075,0.049740,-0.072941,0.074683,0.080619,0.323556,1.000000,0.253135,0.399794,-0.013736,0.056142,-0.101163,-0.108411,-0.097877
Dalc,0.133453,0.001515,-0.000165,0.109423,-0.159665,0.116336,-0.076483,0.144979,0.253135,1.000000,0.627814,0.065515,0.132867,-0.150943,-0.131576,-0.129642
Walc,0.098291,-0.029331,0.019524,0.084292,-0.229073,0.107432,-0.100663,0.130377,0.399794,0.627814,1.000000,0.106669,0.139703,-0.142401,-0.128114,-0.115740
health,-0.029129,-0.013254,0.034288,-0.029002,-0.063044,0.048311,0.104101,0.081517,-0.013736,0.065515,0.106669,1.000000,-0.027479,-0.060478,-0.088001,-0.080079
absences,0.153196,0.059708,0.040829,-0.022669,-0.075594,0.099998,-0.062171,-0.032079,0.056142,0.132867,0.139703,-0.027479,1.000000,-0.092425,-0.089332,-0.045671
G1,-0.124121,0.226101,0.195898,-0.121053,0.211314,-0.374175,0.036947,-0.051985,-0.101163,-0.150943,-0.142401,-0.060478,-0.092425,1.000000,0.858739,0.809142
G2,-0.119475,0.224662,0.182634,-0.140163,0.183167,-0.377172,0.042054,-0.068952,-0.108411,-0.131576,-0.128114,-0.088001,-0.089332,0.858739,1.000000,0.910743
G3,-0.125282,0.201472,0.159796,-0.102627,0.161629,-0.383145,0.054461,-0.064890,-0.097877,-0.129642,-0.115740,-0.080079,-0.045671,0.809142,0.910743,1.000000

## 2.Data Manipulation

In [16]:
# Rename column names
students.columns = ['school','gender','age','address','family_size','parents_status','mother_education','father_education',
           'mother_job','father_job','reason','guardian','commute_time','study_time','failures','school_support',
          'family_support','paid_classes','activities','nursery','desire_higher_edu','internet','romantic','family_quality',
          'free_time','go_out','weekday_alcohol_usage','weekend_alcohol_usage','health','absences','period1_score','period2_score','final_score']

In [23]:
# check if there is missing values
students.isnull().any()

school                   False
gender                   False
age                      False
address                  False
family_size              False
parents_status           False
mother_education         False
father_education         False
mother_job               False
father_job               False
reason                   False
guardian                 False
commute_time             False
study_time               False
failures                 False
school_support           False
family_support           False
paid_classes             False
activities               False
nursery                  False
desire_higher_edu        False
internet                 False
romantic                 False
family_quality           False
free_time                False
go_out                   False
weekday_alcohol_usage    False
weekend_alcohol_usage    False
health                   False
absences                 False
period1_score            False
period2_score            False
final_score              False
dtype: bool